# Generated by Django 6.1 on 2026-10-03 23:38

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('personality_desc', models.CharField(max_length=300)),
                ('coloration', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('hair_type', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('MEDIUM', 'Medium')], max_length=20)),
                ('medical_desc', models.CharField(max_length=300)),
                ('availible', models.BooleanField(default=True)),
            ],
        ),
    ]
