# Generated by Django 6.1 on 2026-10-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='availible',
            new_name='available',
        ),
    ]
