# Generated by Django 6.1 on 2026-10-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_rename_availible_animal_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
